#!/usr/bin/env python3
import argparse
import os
import re
import sys

def check_run_id_safe(run_id: str) -> bool:
    """Check if the provided run_id is filesystem-safe."""
    return bool(re.match(r'^[a-zA-Z0-9_\-]+$', run_id))

def extract_sections(content: str) -> set:
    """Detect presence of required Markdown sections by simple heading matching."""
    sections = set()
    lines = content.split('\n')
    for line in lines:
        if line.startswith('#'):
            lower_line = line.lower()
            if 'problem statement' in lower_line:
                sections.add('Problem Statement')
            elif 'target user' in lower_line:
                sections.add('Target User')
            elif 'current workflow' in lower_line:
                sections.add('Current Workflow')
            elif 'desired outcome' in lower_line:
                sections.add('Desired Outcome')
            elif 'constraints' in lower_line:
                sections.add('Constraints')
            elif 'known risks' in lower_line:
                sections.add('Known Risks')
            elif 'open questions' in lower_line:
                sections.add('Open Questions')
    return sections

def get_base_content(artifact_name: str, status_dict: dict) -> str:
    """Generates the Markdown skeleton for the output artifacts."""
    content = f"# {artifact_name}\n\n"
    content += "```yaml\n"
    for k, v in status_dict.items():
        content += f"{k}: {v}\n"
    content += "```\n\n"
    content += "This artifact is a draft generated by the MVP runner.\n"
    return content

def main():
    parser = argparse.ArgumentParser(description="Minimal Problem Intake Runner MVP")
    parser.add_argument("--input", required=True, help="Path to input Markdown file")
    parser.add_argument("--run-id", required=True, help="Unique run identifier")
    parser.add_argument("--output-root", default="agentos/reports/problem-intake", help="Root output directory")
    args = parser.parse_args()

    input_path = args.input
    run_id = args.run_id
    output_root = args.output_root

    # 1. Error Handling: Input path existence and type checks
    if not os.path.exists(input_path):
        print(f"Error: Input path '{input_path}' does not exist.")
        sys.exit(1)
    if not os.path.isfile(input_path):
        print(f"Error: Input path '{input_path}' is not a file.")
        sys.exit(1)

    # 2. Error Handling: Run ID safety check
    if not check_run_id_safe(run_id):
        print(f"Error: Run ID '{run_id}' is not filesystem-safe.")
        sys.exit(1)

    output_dir = os.path.join(output_root, run_id)

    # 3. Error Handling: Check if output directory already exists
    if os.path.exists(output_dir):
        print(f"Error: Output directory '{output_dir}' already exists. Overwrite is forbidden.")
        sys.exit(1)

    # Read the input file
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            input_content = f.read()
    except Exception as e:
        print(f"Error reading input file: {e}")
        sys.exit(1)

    # Contract: Required sections detection
    required_sections = {
        'Problem Statement',
        'Target User',
        'Current Workflow',
        'Desired Outcome',
        'Constraints',
        'Known Risks',
        'Open Questions'
    }
    found_sections = extract_sections(input_content)
    missing_sections = required_sections - found_sections

    # Determine status fields
    if missing_sections:
        run_status = "INCOMPLETE"
        draft_status = "INCOMPLETE"
        validation_status = "NEEDS_HUMAN_REVIEW"
        approval_status = "NOT_APPROVED"
    else:
        run_status = "DRAFT_CREATED"
        draft_status = "DRAFT_ONLY"
        validation_status = "BASIC_STRUCTURE_CHECKED"
        approval_status = "NOT_APPROVED"

    # Contract: Artifact Semantics
    base_artifact_status = {
        "artifact_status": "DRAFT",
        "approval_status": "NOT_APPROVED",
        "automation_status": "MVP_RUNNER_ONLY",
        "production_status": "NOT_PRODUCTION"
    }

    artifacts = {
        "PROJECT_SPEC.draft.md": get_base_content("Project Spec Draft", base_artifact_status),
        "REQUIREMENTS.draft.md": get_base_content("Requirements Draft", base_artifact_status),
        "problem-interview-report.md": get_base_content("Problem Interview Report", base_artifact_status),
        "requirements-checklist-draft.md": get_base_content("Requirements Checklist Draft", base_artifact_status)
    }

    # Contract: Run Report Semantics
    run_report_status = base_artifact_status.copy()
    run_report_status.update({
        "run_status": run_status,
        "draft_status": draft_status,
        "validation_status": validation_status,
        "approval_status": approval_status
    })

    run_report_content = get_base_content("Problem Intake Run Report", run_report_status)
    if missing_sections:
        run_report_content += f"\nMissing required sections: {', '.join(sorted(missing_sections))}\n"
    else:
        run_report_content += "\nAll required sections found.\n"

    artifacts["problem-intake-run-report.md"] = run_report_content

    # Create output root if missing
    try:
        os.makedirs(output_root, exist_ok=True)
    except Exception as e:
        print(f"Error creating output root '{output_root}': {e}")
        sys.exit(1)

    # Create run output directory
    try:
        os.makedirs(output_dir, exist_ok=False)
    except Exception as e:
        print(f"Error creating output directory '{output_dir}': {e}")
        sys.exit(1)

    # Write artifacts
    for filename, content in artifacts.items():
        filepath = os.path.join(output_dir, filename)
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
        except Exception as e:
            print(f"Error writing artifact '{filename}': {e}")
            sys.exit(1)

    print(f"Draft artifacts successfully saved to '{output_dir}'.")
    print(f"run_status: {run_status}")
    print(f"validation_status: {validation_status}")

if __name__ == "__main__":
    main()
